helmCharts:
  - name: "create-kafka-instance"
    repo: "https://na-launch-workshop.github.io/platform-supporting-charts"
    version: "1.0.0"
    namespace: "${{ values.name }}-kafka"
    valuesInline:
      name: ${{ values.name }}
      userName: ${{ values.userName }}
      kafkaUI:
        enabled: ${{ values.kafkaUIEnabled }}
      topics:
        enabled: ${{ values.topicsEnabled }}
      keda:
        enabled: ${{ values.kedaEnabled }}
