apiVersion: v1
kind: ConfigMap
metadata:
  name: workshop-source-repos
  namespace: gitea
data:
  repos.yaml: |
    gitea_org: developers
    github_org: na-launch-workshop
    repos:
      - name: workshop-devhub-kick-off-scaffolder
        title: "Module 1 - Workshop Devhub Kick Off Scaffolder"

      - name: workshop-quarkus-hello-quarkus
        title: "Module 2 - Workshop Quarkus Hello Quarkus"

      - name: workshop-quarkus-using-camel
        title: "Module 3 - Workshop Quarkus Using Camel"

      - name: workshop-quarkus-using-funqy-stateless-events
        title: "Module 4 - Workshop Quarkus Using Funqy Stateless Events"

      - name: workshop-quarkus-openshift-telemetry-with-micrometer
        title: "Module 5 - Workshop Quarkus Openshift Telemetry With Micrometer"

      - name: workshop-rhoai-models-as-a-service
        title: "Module 6 - Workshop Rhoai Models As A Service"
