resources:
- devspaces-build-ns.yaml
- devspaces-dotnet-python-bc.yaml
- devspaces-dotnet-python-is.yaml
- module-opentelemetry-python-curl-bc.yaml
- module-opentelemetry-python-curl-is.yaml
- rolebinding.yaml
- udi-rhel9-is.yaml
