apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ansible-playbook-template
  title: Create Ansible Playbook Project
  description: Create a new starter Ansible playbook Git project preconfigured with best practices. The project also scaffolds a collection to help get you started.
  tags:
    - recommended
    - ansible
    - playbook
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
    - title: Provide information about the new component
      required:
        - sourceControl
        - repoOwner
        - repoName
        - owner
        - collectionGroup
        - collectionName
      properties:
        sourceControl:
          title: Select source control option
          type: string
          description: Select the source control option for your Ansible project.
          default: gitlab
          enum:
            - gitlab
            - gitea
          enumNames:
            - 'GitLab'
            - 'Gitea'
        repoOwner:
          title: Source code repository organization name
          type: string
          description: The organization name of your source code repository.
          default: developers
          enum:
            - developers
        repoName:
          title: Playbook repository name
          description: The name of the new playbook project repository. For example, “my-new-playbook-repo”.
          type: string
          maxLength: 100
          pattern: '^([a-zA-Z][a-zA-Z0-9_]*)(-[a-zA-Z0-9_]+)*$'
        description:
          title: Playbook description
          type: string
          description: Describe the playbook and its purpose to help other users understand what to use it for.
          maxLength: 350
        collectionGroup:
          title: Playbook project's collection namespace
          description: The collection namespace in your new playbook repository. For example, “my_new_collection_namespace”.
          type: string
          maxLength: 63
          minLength: 2
          pattern: '^[a-z][a-z0-9_]+$'
        collectionName:
          title: Playbook project's collection name
          description: The collection name in your new playbook repository. For example, “my_new_collection_name”.
          type: string
          maxLength: 63
          minLength: 2
          pattern: '^[a-z][a-z0-9_]+$'
        owner:
          title: Catalog Owner name
          type: string
          description: The Red Hat Developer Hub catalog item owner. This will appear on the “My items” tab.
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              kind: User
        system:
          title: System
          type: string
          description: The Red Hat Developer Hub system catalog item name. This will appear on the “My items” tab. For example, “my-devhub-system”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
  steps:
    - id: fetchArgoCDInstances
      name: Fetch ArgoCD Instances
      action: catalog:fetch
      input:
        entityRef: resource:default/argocd-instances

    - id: ansible
      name: Generating the Ansible Source Code Component
      action: ansible:content:create
      input:
        repoOwner: '${{ parameters.repoOwner }}'
        repoName: '${{ parameters.repoName }}'
        description: '${{ parameters.description }}'
        collectionGroup: '${{ parameters.collectionGroup }}'
        collectionName: '${{ parameters.collectionName }}'
        applicationType: playbook-project
        sourceControl: "${{ parameters.sourceControl }}.${{ steps['fetchArgoCDInstances'].output.entity.spec.services.domain }}"

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../catalog-info/
        values:
          repoUrl: ${{ steps.ansible.output.repoUrl }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: playbook-project
          description: ${{ parameters.description }}
          collectionGroup: ${{ parameters.collectionGroup }}
          collectionName: ${{ parameters.collectionName }}
          sourceControl: "${{ parameters.sourceControl }}.${{ steps['fetchArgoCDInstances'].output.entity.spec.services.domain }}"
          devSpacesBaseUrl: ${{ steps.ansible.output.devSpacesBaseUrl }}

    - id: publish-to-gitlab
      name: Publish to GitLab
      action: publish:gitlab
      if: ${{ parameters.sourceControl == 'gitlab' }}
      input:
        repoUrl: "gitlab.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}"
        defaultBranch: main
        settings:
          visibility: internal
        branches:
          - name: main
            protect: true
        gitCommitMessage: Initial commit

    - id: register-gitlab
      name: Registering GitLab Repo in Catalog
      action: catalog:register
      if: ${{ parameters.sourceControl == 'gitlab' }}
      input:
        repoContentsUrl: ${{ steps['publish-to-gitlab'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: publish-to-gitea
      name: Publish to Gitea
      action: publish:gitea
      if: ${{ parameters.sourceControl == 'gitea' }}
      input:
        description: ${{ parameters.description }}
        repoUrl: "gitea.${{ steps['fetchArgoCDInstances'].output.entity.spec.services.domain }}?owner=${{ parameters.repoOwner }}&repo=${{ parameters.repoName }}"
        repoVisibility: 'public'
        defaultBranch: main

    - id: register-gitea
      name: Registering Gitea Repo in Catalog
      action: catalog:register
      if: ${{ parameters.sourceControl == 'gitea' }}
      input:
        repoContentsUrl: ${{ steps['publish-to-gitea'].output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml

  output:
    links:
      - title: Repository
        url: >
          {% if parameters.sourceControl == 'gitlab' -%}
            ${{ steps['publish-to-gitlab'].output.repoContentsUrl }}
          {%- else -%}
            ${{ steps['publish-to-gitea'].output.repoContentsUrl }}
          {%- endif %}

      - title: Open in catalog
        icon: catalog
        entityRef: >
          {% if parameters.sourceControl == 'gitlab' -%}
            ${{ steps['register-gitlab'].output.entityRef }}
          {%- else -%}
            ${{ steps['register-gitea'].output.entityRef }}
          {%- endif %}